release.yml refactor

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -102,7 +102,14 @@ jobs:
           python3 -m pip install pyinstaller
           ./script/build_bootloader.ps1
           ./script/build_win.ps1
-          cp ./dist/win/mapilio-kit--win-64bit.exe mapilio-kit--win-64bit.exe
+          if Test-Path ./dist/win/mapilio-kit--win-64bit.exe; then
+            cp ./dist/win/mapilio-kit--win-64bit.exe mapilio-kit.exe
+          elif Test-Path ./dist/win/mapilio-kit--win-32bit.exe; then
+            cp ./dist/win/mapilio-kit--win-32bit.exe mapilio-kit.exe
+          else
+            echo "Unable to find a suitable Windows executable."
+            exit 1
+          fi
         env:
           MAPILIO_KIT__TESTS_EXECUTABLE: mapilio-kit_WINDOWS_VERY_HARD_TO_FIND_YOU_IN_ANOTHER_DIR_SO_I_MOVE_YOU_HERE.exe
           MAPILIO_KIT__TESTS_EXIFTOOL_EXECUTABLE: perl ${{ github.workspace }}/exiftool/exiftool.pl
